In [ ]:
#Exercice : Statistique avec numpy
Soit le tableau a = np.array([[1,2,3],[4,5,6],[7,8,9]])
1. Afficher la somme des éléments du tableau
2. Afficher la somme des éléments du tableau par colonne
3. Afficher la somme des éléments du tableau par ligne
4. Afficher le produit des éléments du tableau par colonne
5. Afficher le minimum du tableau
6. Afficher le maximum des éléments du tableau
7. Afficher la moyenne des éléments du tableau
8. Afficher la variance des éléments du tableau
9. Afficher l’écart type des éléments du tablea


In [3]:
import numpy as np
# 5. Afficher le minimum du tableau
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a.min()

1

In [5]:
np.min(a)

1

In [31]:
# 1. Afficher la somme des éléments du tableau
np.sum(a)

45

In [32]:
# 2. Afficher la somme des éléments du tableau par colonne
np.sum(a, axis=0)

array([12, 15, 18])

In [33]:
#3. Afficher la somme des éléments du tableau par ligne
np.sum(a, axis=1)

array([ 6, 15, 24])

In [35]:
# 4. Afficher le produit des éléments du tableau par colonne
np.dot(a, axis=0)

TypeError: dot() got an unexpected keyword argument 'axis'

In [10]:
#6. Afficher le maximum des éléments du tableau
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.max()

9

In [11]:
#7. Afficher la moyenne des éléments du tableau
a.mean()

5.0

In [15]:
#8. Afficher la variance des éléments du tableau
np.var(a)

6.666666666666667

In [16]:
a.var()

6.666666666666667

In [18]:
# 9. Afficher l’écart type des éléments du tableau
np.std(a)

2.581988897471611

In [19]:
a.std()

2.581988897471611