In [ ]:
Exercice 1 : les constructeurs
1. Constructeur un tableau numpy qui contient les éléments suivants : 1,5,7,8.
2. Constructeur un tableau numpy qui contient les éléments suivants :
1,2,3,4,5,6,7,8,9
3. Créer un tableau de 10 éléments rempli de 0
4. Créer un tableau de 2 lignes 5 colonnes rempli de 0
5. Créer un tableau de 10 éléments rempli de 1
6. Créer un tableau de 2 lignes 5 colonnes rempli de 1
7. Créer un tableau de 10 éléments rempli 8.5
8. Créer un tableau de série d'entiers successifs allant de 1 à 9 inclus
9. Créer un tableau de 3 lignes et 3 colonnes rempli de série d'entiers successifs
allant de 1 à 9 inclus
10.Créer une matrice identité de 4 lignes 4 colonnes
11. Tableau rempli de valeurs aléatoires normales centrées en zéro
12.Créer un tableau rempli de 20 valeurs aléatoires entières comprises entre 1 et
10
13.Transformer le tableau précédent en matrice de 4 lignes et 5 colonnes
14.Créer un tableau de 5 éléments compris entre 0 et 1 avec une amplitude
égale
Exercice 2 : les attribut

In [7]:
# 1_Constructeur d'un tableau qui contien les éléments[1,5,7,8]
import numpy as np
a=np.array([1, 5, 7, 8])

In [8]:
a

array([1, 5, 7, 8])

In [13]:
# 2_Constructeur d'un tableau qui contien les éléments[1,2,3,4,5,6,7,8,9]
b=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# 3_Créer un tableau de 10 éléments remplis de zero
c=np.array([0]*10)

In [19]:
c

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
#Autre façon de créer un tableau à 10 éléments rempli de zeros
cc=np.zeros([10])


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
import numpy as np
# 4_Créer un tableau de 2 lignes 5 colonnes rempli de 0
#Rmq: tant que l'on ne précise pas le type du contenu, il prend en compte des floats. Raison pour laquelle j'ai mis le typse"int" 
d=np.zeros([2, 5], dtype="int")

In [7]:
d

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
# 5_Tableau de 10 éléments rempli de 1
e=np.array([1]*10)

In [14]:
e

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
#Autre façon d'écrire un tableau de 10 éléments rmpli de 1
ee=np.ones([10])

In [18]:
ee

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
# 6_Créer un tableau de 2 lignes 5 colonnes rempli de 1
# NB: il prend par défaut les éléments en type float
f=np.ones([2, 5])

In [20]:
f

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# 7_Créer un tableau de 10 éléments rempli de 8.5
g=np.array([8.5]*10)

In [22]:
g

array([8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5])

In [38]:
# 8_Créer un tableau de série d'entiers successifs allant de 1 à 9 inclus
#            la fonction arange() permet de construire un array à une dimension de manière simple
#            on peut aussi spécifier une borne de début, une borne de fin et un pas
h=np.arange(1, 10)

In [39]:

h

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
 # Créer un tableau de 3 lignes et 3 colonnes rempli de série d'entiers successifs allant de 1 à 9 inclus
gg=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [80]:
gg

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
# Créer une matrice identité de 4 lignes 4 colonnes
# Matrice identité: le diagonale est tjr rempli de 1
i=np.identity(4)

In [82]:
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
np.random.rand(0,)

array([], dtype=float64)