In [ ]:
Exercice 4 :
1. Créer un tableau de 4 lignes et 3 colonnes rempli de 11 nombres entiers
aléatoires compris entre 0 et 9
2. Quel est le type des éléments du tableau ?
3. Changer de type des éléments du tableau en float32
4. Ajouter le chiffre 3 à la fin du tableau à une dimension
5. Transformer le tableau en matrice dénommée “a” de 3 lignes et 4 colonnes
6. Créer une matrice dénommée “b” de 3 lignes et 4 colonnes remplie de série
d'entiers successifs allant de 1 à 12 inclus
7. Créer une matrice dénommée “c” qui est la concaténation des deux tableaux
“a” et “b” dans le sens horizontale
8. Créer une matrice dénommée “d” qui est la concaténation des deux tableaux
“a” et “b” dans le sens vertical
9. Aplatir un tableau “d”
10.Supprimer dernier élément du tableau

In [57]:
#1. Créer un tableau de 4 lignes et 3 colonnes rempli de 11 nombres entiers aléatoires compris entre 0 et 9
A4=np.zeros((4, 3), dtype = "int")

In [58]:
A4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
A3=A4=np.random.randint(0, 10, size=(4,3))

In [21]:
A3

array([[4, 5, 1],
       [9, 8, 3],
       [6, 3, 8],
       [9, 3, 2]])

In [63]:
# 2. Quel est le type des éléments du tableau ?
A2=A3.dtype

In [64]:
A2

dtype('int32')

In [23]:
# 3. Changer de type des éléments du tableau en float32
A1=np.zeros((4, 3), dtype = "float")

In [67]:
A1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# 3. Changer de type des éléments du tableau en float32
a=np.array([[6, 1, 1], [4, 3, 5], [2, 2, 6], [7, 9, 4]], dtype="float32")

In [43]:
a

array([[6., 1., 1.],
       [4., 3., 5.],
       [2., 2., 6.],
       [7., 9., 4.]], dtype=float32)

In [68]:
# 4. Ajouter le chiffre 3 à la fin du tableau à une dimension
# Nous allons créer un tableau à une dimension
A0=np.zeros((3), dtype = "int")

In [69]:
A0

array([0, 0, 0])

In [70]:
# Ajoutons 3 à la fin du tableau
B4=np.append(A0,3)

In [71]:
B4

array([0, 0, 0, 3])

In [34]:
# 5. Transformer le tableau en matrice dénommée “a” de 3 lignes et 4 colonnes
a=np.array([[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]])
    

In [35]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
import numpy as np
# 6. Créer une matrice dénommée “b” de 3 lignes et 4 colonnes remplie de série d'entiers successifs allant de 1 à 12 inclus
b=np.arange(1,13).reshape(3,4)

In [17]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
b.shape

(4, 3)

In [14]:
#test
arr1 = np.arange(1,10).reshape(3,3)
arr1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 7. Créer une matrice dénommée “c” qui est la concaténation des deux tableaux
# “a” et “b” dans le sens horizontale

In [41]:
c=np.concatenate((a, b), axis=0)
c

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
#8. Créer une matrice dénommée “d” qui est la concaténation des deux tableaux
# "a” et “b” dans le sens vertical
d=np.concatenate((a, b), axis=1)
d

array([[ 0,  0,  0,  0,  1,  2,  3,  4],
       [ 0,  0,  0,  0,  5,  6,  7,  8],
       [ 0,  0,  0,  0,  9, 10, 11, 12]])

In [43]:
# 9. Aplatir un tableau “d”(flatten ou ravel)
e = d.flatten()
e

array([ 0,  0,  0,  0,  1,  2,  3,  4,  0,  0,  0,  0,  5,  6,  7,  8,  0,
        0,  0,  0,  9, 10, 11, 12])

In [47]:
e1 = d.ravel()
e1

array([ 0,  0,  0,  0,  1,  2,  3,  4,  0,  0,  0,  0,  5,  6,  7,  8,  0,
        0,  0,  0,  9, 10, 11, 12])

In [50]:
# 10.Supprimer dernier élément du tableau
f=np.delete(e1, -1)
f

array([ 0,  0,  0,  0,  1,  2,  3,  4,  0,  0,  0,  0,  5,  6,  7,  8,  0,
        0,  0,  0,  9, 10, 11])